#!/usr/bin/env bash
# Source this file from the repository root or from a Slurm job.

CANVASRCA_ROOT="${CANVASRCA_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export CANVASRCA_ROOT
export RL_SLM_RCA_ROOT="${RL_SLM_RCA_ROOT:-$(cd "$CANVASRCA_ROOT/.." && pwd)/RL-SLM-RCA-rw_phase2}"
export SCRATCH="${SCRATCH:-$CANVASRCA_ROOT}"
export CANVASRCA_PROCESSED_ROOT="${CANVASRCA_PROCESSED_ROOT:-$CANVASRCA_ROOT/dataset/processed}"
export CANVASRCA_CACHE_ROOT="${CANVASRCA_CACHE_ROOT:-$SCRATCH/canvasrca_cache}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$CANVASRCA_CACHE_ROOT/matplotlib}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$CANVASRCA_CACHE_ROOT/xdg}"
export HF_HOME="${HF_HOME:-$CANVASRCA_CACHE_ROOT/huggingface}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$CANVASRCA_CACHE_ROOT/triton}"
export TORCHINDUCTOR_CACHE_DIR="${TORCHINDUCTOR_CACHE_DIR:-$CANVASRCA_CACHE_ROOT/torchinductor}"
export CUDA_CACHE_PATH="${CUDA_CACHE_PATH:-$CANVASRCA_CACHE_ROOT/cuda}"
export VLLM_CACHE_ROOT="${VLLM_CACHE_ROOT:-$CANVASRCA_CACHE_ROOT/vllm}"
export VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR="${VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR:-$CANVASRCA_CACHE_ROOT/vllm/flashinfer-autotune}"
export FLASHINFER_WORKSPACE_BASE="${FLASHINFER_WORKSPACE_BASE:-$CANVASRCA_CACHE_ROOT/flashinfer}"
export VLLM_NO_USAGE_STATS=1
export VLLM_DO_NOT_TRACK=1
export VLLM_BASE_URL="${VLLM_BASE_URL:-http://127.0.0.1:8000/v1}"
export VLLM_API_KEY="${VLLM_API_KEY:-EMPTY}"
export CANVASRCA_ATTENTION_PROBE="${CANVASRCA_ATTENTION_PROBE:-1}"
export CANVASRCA_ATTENTION_PROBE_REQUIRED="${CANVASRCA_ATTENTION_PROBE_REQUIRED:-1}"
export CANVASRCA_ATTENTION_DIR="${CANVASRCA_ATTENTION_DIR:-$CANVASRCA_CACHE_ROOT/attention_probe}"
mkdir -p "$MPLCONFIGDIR" "$XDG_CACHE_HOME" "$HF_HOME" "$TRITON_CACHE_DIR" \
  "$TORCHINDUCTOR_CACHE_DIR" "$CUDA_CACHE_PATH" "$VLLM_CACHE_ROOT" \
  "$VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR" "$FLASHINFER_WORKSPACE_BASE" \
  "$CANVASRCA_ATTENTION_DIR"
export MPLBACKEND=Agg
export PYTHONUNBUFFERED=1
export PYTHONPATH="$CANVASRCA_ROOT/src:$CANVASRCA_ROOT${PYTHONPATH:+:$PYTHONPATH}"

CANVASRCA_ENV="${CANVASRCA_ENV:-$CANVASRCA_ROOT/.venv-base}"
if [[ -f "$CANVASRCA_ENV/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "$CANVASRCA_ENV/bin/activate"
fi
