#!/usr/bin/env bash
# Source this file before activating the CanvasRCA virtual environment.

CANVASRCA_MODULE_MODE="${1:-base}"
CANVASRCA_STDENV_MODULE="${CANVASRCA_STDENV_MODULE:-StdEnv/2023}"
CANVASRCA_COMPILER_MODULE="${CANVASRCA_COMPILER_MODULE:-gcc/12.3}"
CANVASRCA_PYTHON_MODULE="${CANVASRCA_PYTHON_MODULE:-python/3.11.5}"
CANVASRCA_ARROW_MODULE="${CANVASRCA_ARROW_MODULE:-arrow/25.0.0}"
CANVASRCA_OPENCV_MODULE="${CANVASRCA_OPENCV_MODULE:-opencv/4.13.0}"
CANVASRCA_CUDA_MODULE="${CANVASRCA_CUDA_MODULE:-cuda/12.6}"
export CANVASRCA_STDENV_MODULE CANVASRCA_COMPILER_MODULE
export CANVASRCA_PYTHON_MODULE CANVASRCA_ARROW_MODULE CANVASRCA_OPENCV_MODULE
export CANVASRCA_CUDA_MODULE

if command -v module >/dev/null 2>&1; then
  module --force purge
  module load "$CANVASRCA_STDENV_MODULE"
  module load "$CANVASRCA_COMPILER_MODULE"
  module load "$CANVASRCA_PYTHON_MODULE"
  module load "$CANVASRCA_ARROW_MODULE"
  if [[ "$CANVASRCA_MODULE_MODE" == "inference" || "$CANVASRCA_MODULE_MODE" == "all" ]]; then
    module load "$CANVASRCA_OPENCV_MODULE"
    module load "$CANVASRCA_CUDA_MODULE"
  fi
fi

unset CANVASRCA_MODULE_MODE
